baseURL = "https://emanuelpina.pt/"
languageCode = "en-gb"
title = "Emanuel Pina"
theme = "mytheme"

metaDataFormat = "yaml"

enableRobotsTXT = true

pygmentsUseClasses = "true"
pygmentsCodeFences = "true"
pygmentsOptions = "linenos=table"

paginatePath= "page"

enableEmoji= true

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[params]
  author = "Emanuel Pina"
  description = "Blog de Emanuel Pina"
  readmore = "Read more..."
  paginationpath = "page"
  imagecdn = "https://img.emanuelpina.com/"

[permalinks]
  posts = "/:title/"
  categories = "/categories/:title/"
  tags = "/tags/:title/"
