[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://emanuelpina.netlify.com/*"
  to = "https://emanuelpina.pt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://emanuelpina.com/*"
  to = "https://emanuelpina.pt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.emanuelpina.com/*"
  to = "https://emanuelpina.pt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://e.mnlpn.xyz/*"
  to = "https://emanuelpina.pt/:splat"
  status = 301
  force = true