name = "MyTheme"
license = "MIT"
licenselink = "https://github.com/emanuelpina/blog/blob/master/LICENSE"
description = "A tailor-made theme for my personal blog"
homepage = "https://emanuelpina.pt/"
tags = ["blog", "personal"]
features = ["taxonomies", "pagination", "contact form", "commento", "shortcodes", "pygments", "netlify"]
min_version = "0.58.0"

[author]
  name = "Emanuel Pina"
  homepage = "https://emanuelpina.pt/"
